defaults:
  - override hydra/launcher: submitit_slurm
  - override hydra/sweeper: wandb
  - _self_

experiment:
  name: test_experiment
  db: cifar
  lr: 0.01
  batch_size: 8

model:
  name: test_model
  dropout: 0.6

hydra:
  mode: MULTIRUN
  job:
    chdir: false
  run: # don't put outputs in HOME, use SCRATCH instead
    dir: ./logs/run/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./logs/sweep/${now:%Y-%m-%d}/${now:%H-%M-%S}
